#!/bin/bash
#
# Runs the test version of this app

mv wscript wscript-build
mv wscript-test wscript
pebble build
pebble install --emulator basalt --logs >> test_log.txt &
mv wscript wscript-test
mv wscript-build wscript